# Webex Contact Center BYOVA Gateway Configuration Template
# This template supports environment variable substitution
# Use this for production deployments

# Gateway settings
gateway:
  host: "${GATEWAY_HOST:-0.0.0.0}"
  port: ${GATEWAY_PORT:-50051}

# Connectors configuration
connectors:
  # Local Audio Connector
  local_audio_connector:
    type: "local_audio_connector"
    class: "LocalAudioConnector"
    module: "connectors.local_audio_connector"
    config:
      audio_files:
        welcome: "welcome.wav"
        transfer: "transferring.wav"
        goodbye: "goodbye.wav"
        error: "error.wav"
        default: "default_response.wav"
      agents:
        - "Local Playback"

  # AWS Lex Connector
  aws_lex_connector:
    type: "aws_lex_connector"
    class: "AWSLexConnector"
    module: "connectors.aws_lex_connector"
    config:
      region_name: "${AWS_REGION:-us-east-1}"
      bot_alias_id: "${AWS_LEX_BOT_ALIAS_ID:-TSTALIASID}"
      bot_name: "${AWS_LEX_BOT_NAME:-}"
      locale: "${AWS_LEX_LOCALE:-en_US}"
      
      # Barge-in configuration (default: false)
      # When enabled, users can interrupt the bot's response
      barge_in_enabled: false
      
      # Audio logging configuration
      audio_logging:
        enabled: true
        output_dir: "/app/logs/audio_recordings"
        filename_format: "{conversation_id}_{timestamp}_{source}.wav"
        log_all_audio: true
        max_file_size: 10485760
        sample_rate: 8000
        bit_depth: 8
        channels: 1
        encoding: "ulaw"
      agents: []

# Monitoring interface
monitoring:
  enabled: true
  host: "${MONITORING_HOST:-0.0.0.0}"
  port: ${MONITORING_PORT:-8080}
  metrics_enabled: true
  health_check_interval: 30

# Logging configuration
logging:
  gateway:
    level: "${LOG_LEVEL:-INFO}"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "/app/logs/gateway.log"
    max_size: "10MB"
    backup_count: 5
  
  web:
    level: "WARNING"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "/app/logs/web.log"
    max_size: "5MB"
    backup_count: 3

# Session management
sessions:
  timeout: 600
  max_sessions: 1000
  cleanup_interval: 60
  enable_auto_cleanup: true
  max_session_duration: 3600

# Audio processing
audio:
  supported_formats:
    - "wav"
    - "mp3"
    - "flac"
    - "ogg"





